use portfolioproject;
CREATE TABLE `coviddeaths` (
  --  `id` int not null auto_increment primary key, 
  `iso_code` text,
  `continent` text,
  `location` text,
  `date` date DEFAULT NULL,
  `population` int DEFAULT NULL,
  `total_cases` int DEFAULT NULL,
  `new_cases` int DEFAULT NULL,
  `new_cases_smoothed` double DEFAULT NULL,
  `total_deaths` double DEFAULT NULL,
  `new_deaths` double DEFAULT NULL,
  `new_deaths_smoothed` double DEFAULT NULL,
  `total_cases_per_million` double DEFAULT NULL,
  `new_cases_per_million` double DEFAULT NULL,
  `new_cases_smoothed_per_million` double DEFAULT NULL,
  `total_deaths_per_million` double DEFAULT NULL,
  `new_deaths_per_million` double DEFAULT NULL,
  `new_deaths_smoothed_per_million` double DEFAULT NULL,
  `reproduction_rate` double DEFAULT NULL,
  `icu_patients` double DEFAULT NULL,
  `icu_patients_per_million` double DEFAULT NULL,
  `hosp_patients` double DEFAULT NULL,
  `hosp_patients_per_million` double DEFAULT NULL,
  `weekly_icu_admissions` double DEFAULT NULL,
  `weekly_icu_admissions_per_million` double DEFAULT NULL,
  `weekly_hosp_admissions` double DEFAULT NULL,
  `weekly_hosp_admissions_per_million` double DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
